import os
import shutil
import subprocess
import sys

# Ensures this script is run in a directory with a markdown/ and a src/,
# and markdown is installed.
def SanityCheck():
  _, dirnames, _ = os.walk('.').next()
  if 'markdown' not in dirnames or 'src' not in dirnames:
    print '%s must be run inside a directory with a markdown/ and a src/.' % (
        os.path.basename(__file__))
    return False

  if subprocess.call(['which', 'markdown'], stdout=subprocess.PIPE,
                     stderr=subprocess.PIPE):
    print 'markdown not installed. Type: sudo apt-get install markdown'
    return False

  return True

# Generates .html files from .md files in markdown/.
def GenerateHtml():
  for dirpath, _, filenames in os.walk('markdown'):
    for filename in filenames:
      if filename.endswith('.md'):
        src = os.path.join(dirpath, filename)
        dst = src[:-2] + 'html'

        p = subprocess.Popen(['markdown', src], stdout=subprocess.PIPE)

        html, err = p.communicate()
        if err:
          print 'markdown %s > %s' % (src, dst)
          print '  [ERROR]: %s' % err
          continue

        f = open(dst, 'w')
        f.write(html)
        f.close()

# Moves .html files generated by markdown from markdown/ to their corresponding
# location in src/.
def MoveHtml():
  for dirpath, _, filenames in os.walk('markdown'):
    for filename in filenames:
      if filename.endswith('.html'):
        src = os.path.join(dirpath, filename)
        # Better than src.replace('markdown/', 'src/') because there may be more
        # than one 'markdown/' in src.
        dst = 'src/' + src[9:]

        try:
          shutil.move(src, dst)
        except Exception, e:
          print '%s -> %s' % (src, dst)
          print '  %s. Did you forget to mkdir %s/?' % (e, dst[:dst.rfind('/')])

def main():
  if not SanityCheck():
    return 1

  GenerateHtml()
  MoveHtml()

if __name__ == '__main__':
  main()
