import os
import shutil
import subprocess
import sys

# Ensures this script is run in a directory with a markdown/ and a src/.
def SanityCheck():
  _, dirnames, _ = os.walk('.').next()
  if 'markdown' not in dirnames or 'src' not in dirnames:
    print '%s must be run inside a directory with a markdown/ and a src/.' % (
        os.path.basename(__file__))
    sys.exit(1)

# Generates .html files from .md files in markdown/.
def GenerateHtml():
  for dirpath, _, filenames in os.walk('markdown'):
    for filename in filenames:
      if filename.endswith('.md'):
        src = os.path.join(dirpath, filename)
        dst = src[:-2] + 'html'

        try:
          p = subprocess.Popen(['markdown', src], stdout=subprocess.PIPE)
        except OSError, e:
          print 'OSError: %s.' % e
          print ('Did you forget to install markdown? sudo apt-get install '
              'markdown')
          sys.exit(1)


        print 'Generating %s from %s' % (dst, src)
        html, err = p.communicate()
        if err:
          print '  [ERROR]: %s' % err
          continue

        f = open(dst, 'w')
        f.write(html)
        f.close()

# Moves .html files generated by markdown from markdown/ to their corresponding
# location in src/.
def MoveHtml():
  for dirpath, _, filenames in os.walk('markdown'):
    for filename in filenames:
      if filename.endswith('.html'):
        src = os.path.join(dirpath, filename)
        # Better than src.replace('markdown/', 'src/') because there may be more
        # than one 'markdown/' in src.
        dst = 'src/' + src[9:]

        print '%s -> %s' % (src, dst)
        try:
          shutil.move(src, dst)
        except Exception, e:
          print '  %s. Did you forget to mkdir %s/?' % (e, dst[:dst.rfind('/')])

def main():
  SanityCheck()
  GenerateHtml()
  MoveHtml()

if __name__ == '__main__':
  main()
